import type { Metadata } from "next";
import "./globals.css";
import { Inter, Montaga } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "800", "900", "700"],
  variable: "--font-inter", // CSS variable for Inter
});

// Initialize Montaga font
const montaga = Montaga({
  subsets: ["latin"],
  weight: "400", // Montaga typically has one weight
  variable: "--font-montaga", // CSS variable for Montaga
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${montaga.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
